local tab_modules = {
	"plugins.configs.impatient",
	"plugins.configs.alpha",
	"plugins.configs.vsnip",
	"plugins.configs.icons",
	"core.lsp",
	"plugins.configs.cmp-nvim",
	"plugins.configs.treesitter-nvim",
	"plugins.configs.devicons",
	"plugins.configs.nvimtree",
	"plugins.configs.formatter",
	"plugins.configs.gitsigns",
	"plugins.configs.colorizer",
	"plugins.configs.statusline",
	--"yoliani.statusline",
	"plugins.configs.bufferline",
	"plugins.configs.telescope",
	"plugins.configs.whichkey",
	"plugins.configs.autopairs",
	"plugins.configs.go-preview",
	"plugins.configs.todo-comments",
	"plugins.configs.dap",
	"plugins.configs.neorg",
	"plugins.configs.notify",
	"plugins.configs.comments",
	"plugins.configs.themes",
	"plugins.configs.presence",
	"plugins.configs.vgit",
	"plugins.configs.copilot",
	"plugins.configs.neoroot",
	"plugins.configs.workspaces-sessions",
	"plugins.configs.octo",
	"plugins.configs.pretty-fold",
}

for i = 1, #tab_modules, 1 do
 ey.safe_require(tab_modules[i])
end
